module.exports = [
  {
    country: 'IT',
    destinations: [
        { code: 'AHO01@1', name: 'Alghero Airport', type: 'airport' },
        { code: 'AOI02', name: 'Ancona Airport', type: 'airport' },
        { code: 'AOT01', name: 'Aosta Airport', type: 'airport' },
        { code: 'BRI01', name: 'Bari Airport', type: 'airport' },
        { code: 'BGY01', name: 'Bergamo Airport', type: 'airport' },
        { code: 'BLQ01', name: 'Bologna Airport', type: 'airport' },
        { code: 'BZO01', name: 'Bolzano Airport', type: 'airport' },
        { code: 'BDS01', name: 'Brindisi Airport', type: 'airport' },
        { code: 'CAG01@1', name: 'Cagliari Airport', type: 'airport' },
        { code: 'CTA01@1', name: 'Catania Airport', type: 'airport' },
        { code: 'COM02@1', name: 'Comiso Airport', type: 'airport' },
        { code: 'CUF02', name: 'Cuneo Airport', type: 'airport' },
        { code: 'EBA01', name: 'Elba Airport', type: 'airport' },
        { code: 'FCO01@1', name: 'Fiumicino Airport', type: 'airport' },
        { code: 'FLR03', name: 'Florence Airport', type: 'airport' },
        { code: 'FRL01', name: 'Forlì Airport', type: 'airport' },
        { code: 'GOA01', name: 'Genoa Airport', type: 'airport' },
        { code: 'SUF01', name: 'Lamezia Terme Airport', type: 'airport' },
        { code: 'MIA01', name: 'Milan Linate Airport', type: 'airport' },
        { code: 'MXP01', name: 'Milan Malpensa Airport', type: 'airport' },
        { code: 'NAP01', name: 'Naples Airport', type: 'airport' },
        { code: 'OLB01@1', name: 'Olbia Airport', type: 'airport' },
        { code: 'PMO01@1', name: 'Palermo Airport', type: 'airport' },
        { code: 'PMF01', name: 'Parma Airport', type: 'airport' },
        { code: 'PEG03', name: 'Perugia Airport', type: 'airport' },
        { code: 'PSR03', name: 'Pescara Airport', type: 'airport' },
        { code: 'PSA01', name: 'Pisa Airport', type: 'airport' },
        { code: 'REG02', name: 'Reggio Calabria Airport', type: 'airport' },
        { code: 'RMI02', name: 'Rimini Airport', type: 'airport' },
        { code: 'CIA01', name: 'Rome Ciampino Airport', type: 'airport' },
        { code: 'FCO01', name: 'Rome Fiumicino Airport', type: 'airport' },
        { code: 'AHO01', name: 'Sardinia - Alghero Airport', type: 'airport' },
        { code: 'CAG01', name: 'Sardinia - Cagliari Airport', type: 'airport' },
        { code: 'OLB01', name: 'Sardinia - Olbia Airport', type: 'airport' },
        { code: 'CTA01', name: 'Sicily - Catania Airport', type: 'airport' },
        { code: 'COM02', name: 'Sicily - Comiso Airport', type: 'airport' },
        { code: 'PMO01', name: 'Sicily - Palermo Airport', type: 'airport' },
        { code: 'PNL01', name: 'Sicily - Pantelleria Airport', type: 'airport' },
        { code: 'TPS01', name: 'Sicily - Trapani Airport', type: 'airport' },
        { code: 'MXP02', name: 'Somma Lombardo Airport', type: 'airport' },
        { code: 'TPS01@1', name: 'Trapani Airport', type: 'airport' },
        { code: 'TSF01', name: 'Treviso Airport', type: 'airport' },
        { code: 'TRS01', name: 'Trieste Airport', type: 'airport' },
        { code: 'TRN01', name: 'Turin Airport', type: 'airport' },
        { code: 'VCE01', name: 'Venice Airport', type: 'airport' },
        { code: 'VRN01', name: 'Verona Airport', type: 'airport' } 
      ]
  }
]
